[package]
name = "durin-primitives"
description = "Primitive types for Durin."
authors = ["clabby"]

version.workspace = true

[dependencies]
alloy-primitives = { git = "https://github.com/alloy-rs/core.git" }
anyhow = "1.0.75"
tracing = "0.1.37"
