[package]
name = "durin-fault"
description = "Game solver for the OP Stack's FaultDisputeGame"
authors = ["clabby"]

version.workspace = true

[dependencies]
# Internal
durin-primitives = { path = "../primitives" }

# External
alloy-primitives = { git = "https://github.com/alloy-rs/core.git" }
alloy-sol-types = { git = "https://github.com/alloy-rs/core.git" }
anyhow = "1.0.75"
